"""empty message

Revision ID: 002bedc070dd
Revises: 37946f892f2d
Create Date: 2025-04-05 16:47:50.973750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002bedc070dd'
down_revision: Union[str, None] = '37946f892f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apple_devices',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('device_registrations',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('pass_type_id', sa.String(), nullable=False),
    sa.Column('serial_number', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['apple_devices.device_id'], ),
    sa.PrimaryKeyConstraint('device_id', 'pass_type_id', 'serial_number')
    )
    op.add_column('event_ticket', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('member_card', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_card', 'last_updated')
    op.drop_column('event_ticket', 'last_updated')
    op.drop_table('device_registrations')
    op.drop_table('apple_devices')
    # ### end Alembic commands ###
