"""empty message

Revision ID: 07a488ec8c0a
Revises: ce39ee430ef6
Create Date: 2025-10-30 02:22:38.511963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a488ec8c0a'
down_revision: Union[str, None] = 'ce39ee430ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='refresh_token_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refresh_token_pkey'),
    sa.UniqueConstraint('token', name='refresh_token_token_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
