"""person status enum

Revision ID: 196e87235d1c
Revises: 6bb500d8c8c4
Create Date: 2025-06-05 14:31:33.155199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196e87235d1c'
down_revision: Union[str, None] = '6bb500d8c8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE personstatus AS ENUM ('pending', 'approved', 'rejected')")

    op.add_column('person', sa.Column('status', sa.Enum(
        'pending', 'approved', 'rejected', name='personstatus'), nullable=False, server_default='pending'))
    op.drop_column('person', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_verified', sa.BOOLEAN(),
                  autoincrement=False, nullable=True))
    op.drop_column('person', 'status')
    op.execute("DROP TYPE personstatus")

    # ### end Alembic commands ###
