"""empty message

Revision ID: 1cbf1585ba8f
Revises: 4b3ed66e1b03
Create Date: 2025-12-17 19:23:28.891438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbf1585ba8f'
down_revision: Union[str, None] = '4b3ed66e1b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('referer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'person', 'person', ['referer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'referer_id')
    # ### end Alembic commands ###
