"""fn and ln

Revision ID: 24bc48780717
Revises: a6e97c1362c9
Create Date: 2025-11-10 01:13:12.910046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bc48780717'
down_revision: Union[str, None] = 'a6e97c1362c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('first_name', sa.String(), server_default='fn', nullable=False))
    op.add_column('person', sa.Column('last_name', sa.String(), server_default='ln', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'last_name')
    op.drop_column('person', 'first_name')
    # ### end Alembic commands ###
