"""add early bird tickets

Revision ID: 27354982ebff
Revises: 4eace5341803
Create Date: 2025-09-04 22:14:06.888740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27354982ebff'
down_revision: Union[str, None] = '4eace5341803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('early_bird_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event', sa.Column('general_admission_price', sa.Integer(), nullable=True))
    op.alter_column('event', 'ticket_price', new_column_name='early_bird_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ticket_price', sa.INTEGER(),
                  autoincrement=False, nullable=True))
    op.drop_column('event', 'general_admission_price')
    op.drop_column('event', 'early_bird_price')
    op.drop_column('event', 'early_bird_date')
    # ### end Alembic commands ###
