"""add pass urls

Revision ID: 2b0ab9a99657
Revises: 3ac305271cc6
Create Date: 2025-04-02 15:00:57.222786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0ab9a99657'
down_revision: Union[str, None] = '3ac305271cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_card', sa.Column('apple_pass_url', sa.String(), nullable=True))
    op.add_column('member_card', sa.Column('google_pass_url', sa.String(), nullable=True))
    op.add_column('person', sa.Column('apple_pass_url', sa.String(), nullable=True))
    op.add_column('person', sa.Column('google_pass_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'google_pass_url')
    op.drop_column('person', 'apple_pass_url')
    op.drop_column('member_card', 'google_pass_url')
    op.drop_column('member_card', 'apple_pass_url')
    # ### end Alembic commands ###
