"""nullable and non-nullable fields

Revision ID: 2ba2bfaf40e7
Revises: 243610bf45e2
Create Date: 2025-10-04 22:11:06.741640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ba2bfaf40e7'
down_revision: Union[str, None] = '243610bf45e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('event', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('event', 'general_admission_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event', 'member_ticket_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event', 'max_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'max_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event', 'member_ticket_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event', 'general_admission_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('event', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
