"""empty message

Revision ID: 30c2dd4c1bf4
Revises: 3e535fac4aff
Create Date: 2025-10-19 13:20:46.546866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c2dd4c1bf4'
down_revision: Union[str, None] = '3e535fac4aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'short_name')
    # ### end Alembic commands ###
