"""empty message

Revision ID: 318de933a7ed
Revises: 9d37fe888aee
Create Date: 2025-10-14 01:57:30.453890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '318de933a7ed'
down_revision: Union[str, None] = '9d37fe888aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_old')
    op.add_column('event_ticket', sa.Column('created_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('event_ticket', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=True, onupdate=sa.text('now()')))
    op.add_column('event_ticket', sa.Column(
        'attended_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('event_ticket', 'last_updated')
    op.drop_column('event_ticket', 'is_sent')
    op.drop_column('event_ticket', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket', sa.Column(
        'is_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('event_ticket', sa.Column('last_updated', postgresql.TIMESTAMP(
        timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('event_ticket', 'attended_at')
    op.drop_column('event_ticket', 'updated_at')
    op.drop_column('event_ticket', 'created_at')
    op.create_table('payment_old',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), autoincrement=False, nullable=False),
                    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('request_id', sa.VARCHAR(length=36),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('pay_url', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('status', postgresql.ENUM('CONFIRMED', 'REJECTED', 'PENDING', 'REFUNDED',
                                                        'CREATED', name='paymentstatus'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id'],
                                            name='payment_event_id_fkey'),
                    sa.ForeignKeyConstraint(['person_id'], ['person.id'],
                                            name='payment_person_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='payment_pkey')
                    )
    # ### end Alembic commands ###
