"""empty message

Revision ID: 33096dc8c28d
Revises: 30c2dd4c1bf4
Create Date: 2025-10-19 13:45:22.235314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33096dc8c28d'
down_revision: Union[str, None] = '30c2dd4c1bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
