"""maps link non-null

Revision ID: 397ddf42cfb5
Revises: 991e0a14a563
Create Date: 2025-09-23 00:52:29.612105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397ddf42cfb5'
down_revision: Union[str, None] = '991e0a14a563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'yandex_maps_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'yandex_maps_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
