"""empty message

Revision ID: 3e535fac4aff
Revises: 318de933a7ed
Create Date: 2025-10-14 17:27:21.620057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e535fac4aff'
down_revision: Union[str, None] = '318de933a7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_pass', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('member_pass', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('member_pass', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_pass', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('member_pass', 'updated_at')
    op.drop_column('member_pass', 'created_at')
    # ### end Alembic commands ###
