"""recreate everything

Revision ID: 46cfcff5b6c3
Revises: 002bedc070dd
Create Date: 2025-04-05 20:16:30.990242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cfcff5b6c3'
down_revision: Union[str, None] = '002bedc070dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apple_devices',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('person',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('instagram_handle', sa.String(), nullable=True),
    sa.Column('telegram_handle', sa.String(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('venues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=False),
    sa.Column('venue_address', sa.String(), nullable=True),
    sa.Column('venue_location', sa.String(), nullable=False),
    sa.Column('venue_maps_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_registrations',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('pass_type_id', sa.String(), nullable=False),
    sa.Column('serial_number', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['apple_devices.device_id'], ),
    sa.PrimaryKeyConstraint('device_id', 'pass_type_id', 'serial_number')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('doors_open', sa.Time(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_card',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('apple_pass_url', sa.String(), nullable=True),
    sa.Column('google_pass_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('event_ticket',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('apple_pass_url', sa.String(), nullable=True),
    sa.Column('google_pass_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'event_id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('event_ticket_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['event_ticket_id'], ['event_ticket.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('event_ticket')
    op.drop_table('member_card')
    op.drop_table('event')
    op.drop_table('device_registrations')
    op.drop_table('venues')
    op.drop_table('person')
    op.drop_table('apple_devices')
    # ### end Alembic commands ###
