"""Add server defaults

Revision ID: 49b4c48ee0c9
Revises: 67cf567a7ceb
Create Date: 2025-08-19 23:24:42.533539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '49b4c48ee0c9'
down_revision: Union[str, None] = '67cf567a7ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        'event_ticket',
        'last_updated',
        existing_type=sa.DateTime(timezone=True),
        server_default=func.now()
    )
    pass
    # ### end Alembic commands ###
    op.alter_column(
        'member_card',
        'last_updated',
        existing_type=sa.DateTime(timezone=True),
        server_default=func.now()
    )
    pass
    # ### end Alembic commands ###
    op.alter_column(
        'attendance',
        'date_modified',
        existing_type=sa.DateTime(timezone=True),
        server_default=func.now()
    )
    pass
    # ### end Alembic commands ###
    op.alter_column(
        'payment',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        server_default=func.now()
    )
    pass
    # ### end Alembic commands ###
    op.alter_column(
        'payment',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        server_default=func.now()
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
