"""drop column doors_open

Revision ID: 4eace5341803
Revises: f0e3d3af0e69
Create Date: 2025-08-20 02:28:58.398456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eace5341803'
down_revision: Union[str, None] = 'f0e3d3af0e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'starts_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.drop_column('event', 'doors_open')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('doors_open', postgresql.TIME(
        timezone=True), autoincrement=False, nullable=False))
    op.alter_column('event', 'starts_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    # ### end Alembic commands ###
