"""payment logic change part 2

Revision ID: 5751d88e8515
Revises: e003b79f88be
Create Date: 2025-09-24 03:12:21.004059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from enums import PaymentStatus


# revision identifiers, used by Alembic.
revision: str = '5751d88e8515'
down_revision: Union[str, None] = 'e003b79f88be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
                    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('payment_provider', sa.String(length=50), nullable=False),
                    sa.Column('upstream_payment_id', sa.String(length=255), nullable=True),
                    sa.Column('payment_url', sa.String(length=500), nullable=True),
                    sa.Column('status', postgresql.ENUM(
                        name='paymentstatus', create_type=False), nullable=False, default=PaymentStatus.CREATED),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              nullable=True, onupdate=sa.text('now()')),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    op.create_index(op.f('ix_payment_email'), 'payment', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_email'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
