"""make pass urls nullable

Revision ID: 615ef3c11b0c
Revises: 6a7695355165
Create Date: 2025-09-28 18:27:36.847583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615ef3c11b0c'
down_revision: Union[str, None] = '6a7695355165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_ticket', 'apple_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_ticket', 'google_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_ticket', 'google_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event_ticket', 'apple_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
