"""empty message

Revision ID: 63a7a56448c0
Revises: 93a164c61bf5
Create Date: 2025-06-11 14:06:27.603170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a7a56448c0'
down_revision: Union[str, None] = '93a164c61bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_member')
    op.drop_column('person', 'payment_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('payment_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('is_member', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
