"""Add timezone to event times

Revision ID: 67cf567a7ceb
Revises: 96df9d5c0b92
Create Date: 2025-08-19 23:23:46.638343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67cf567a7ceb'
down_revision: Union[str, None] = '96df9d5c0b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'doors_open',
                    existing_type=postgresql.TIME(),
                    type_=sa.Time(timezone=True),
                    existing_nullable=False)
    op.alter_column('event', 'start_time',
                    existing_type=postgresql.TIME(),
                    type_=sa.Time(timezone=True),
                    existing_nullable=False)
    op.alter_column('event', 'end_time',
                    existing_type=postgresql.TIME(),
                    type_=sa.Time(timezone=True),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'end_time',
                    existing_type=sa.Time(timezone=True),
                    type_=postgresql.TIME(),
                    existing_nullable=True)
    op.alter_column('event', 'start_time',
                    existing_type=sa.Time(timezone=True),
                    type_=postgresql.TIME(),
                    existing_nullable=False)
    op.alter_column('event', 'doors_open',
                    existing_type=sa.Time(timezone=True),
                    type_=postgresql.TIME(),
                    existing_nullable=False)
    # ### end Alembic commands ###
