"""add payment order id FK in Event Ticket

Revision ID: 6a7695355165
Revises: 970e6e95e8ad
Create Date: 2025-09-26 12:00:59.411117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7695355165'
down_revision: Union[str, None] = '970e6e95e8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket', sa.Column('payment_order_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'event_ticket', 'payment', ['payment_order_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_ticket', type_='foreignkey')
    op.drop_column('event_ticket', 'payment_order_id')
    # ### end Alembic commands ###
