"""empty message

Revision ID: 6bb500d8c8c4
Revises: 999ba4471980
Create Date: 2025-06-05 14:17:20.369040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb500d8c8c4'
down_revision: Union[str, None] = '999ba4471980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('device_registrations', 'apple_device_registrations')
    op.create_unique_constraint(None, 'event', ['event_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    op.rename_table('apple_device_registrations', 'device_registrations')

    # ### end Alembic commands ###
