"""add event image and description

Revision ID: 700d7b048ee7
Revises: 196e87235d1c
Create Date: 2025-06-05 23:47:25.565572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700d7b048ee7'
down_revision: Union[str, None] = '196e87235d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('event', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'description')
    op.drop_column('event', 'image_url')
    # ### end Alembic commands ###
