"""upstream paymentid is uuid

Revision ID: 71189067975f
Revises: ffa47fd0c1de
Create Date: 2025-09-24 19:09:27.912683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71189067975f'
down_revision: Union[str, None] = 'ffa47fd0c1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE payment ALTER COLUMN upstream_payment_id TYPE UUID USING upstream_payment_id::uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'upstream_payment_id',
                    existing_type=sa.UUID(),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
