"""Add tz data to datetimes

Revision ID: 7bf722ce96fb
Revises: 49460aa93fff
Create Date: 2025-08-19 19:23:46.613763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bf722ce96fb'
down_revision: Union[str, None] = '49460aa93fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Attendance: values are stored in UTC+4, convert properly to UTC
    op.execute("""
        ALTER TABLE attendance
        ALTER COLUMN date_modified TYPE timestamptz
        USING date_modified AT TIME ZONE 'UTC+4'
    """)

    # Event_ticket & Member_card: assuming these are already UTC
    op.execute("""
        ALTER TABLE event_ticket
        ALTER COLUMN last_updated TYPE timestamptz
        USING last_updated AT TIME ZONE 'UTC'
    """)
    op.execute("""
        ALTER TABLE member_card
        ALTER COLUMN last_updated TYPE timestamptz
        USING last_updated AT TIME ZONE 'UTC'
    """)

    # Payment: already UTC, just tag them
    op.execute("""
        ALTER TABLE payment
        ALTER COLUMN created_at TYPE timestamptz
        USING created_at AT TIME ZONE 'UTC'
    """)
    op.execute("""
        ALTER TABLE payment
        ALTER COLUMN updated_at TYPE timestamptz
        USING updated_at AT TIME ZONE 'UTC'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'updated_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('payment', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('member_card', 'last_updated',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('event_ticket', 'last_updated',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('attendance', 'date_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    # ### end Alembic commands ###
