"""empty message

Revision ID: 831433ce6782
Revises: 0866af719fe6
Create Date: 2025-11-18 22:20:58.359091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831433ce6782'
down_revision: Union[str, None] = '0866af719fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'video_url')
    # ### end Alembic commands ###
