"""payment table column fixes

Revision ID: 8a6e6ebaabc8
Revises: 5751d88e8515
Create Date: 2025-09-24 03:25:42.414320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6e6ebaabc8'
down_revision: Union[str, None] = '5751d88e8515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('event_id', sa.UUID(), nullable=False))
    op.add_column('payment', sa.Column('person_id', sa.UUID(), nullable=False))
    op.drop_index('ix_payment_email', table_name='payment')
    op.create_foreign_key(None, 'payment', 'person', ['person_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'event', ['event_id'], ['id'])
    op.drop_column('payment', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('email', sa.VARCHAR(
        length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_index('ix_payment_email', 'payment', ['email'], unique=False)
    op.drop_column('payment', 'person_id')
    op.drop_column('payment', 'event_id')
    # ### end Alembic commands ###
