"""empty message

Revision ID: 8db647e095e8
Revises: 63a7a56448c0
Create Date: 2025-06-13 17:51:46.504242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db647e095e8'
down_revision: Union[str, None] = '63a7a56448c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('venue', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('venue', 'venue_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('venue_location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'longitude')
    op.drop_column('venue', 'latitude')
    # ### end Alembic commands ###
