"""empty message

Revision ID: 93a164c61bf5
Revises: ddf9e085cc21
Create Date: 2025-06-08 17:42:02.404667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a164c61bf5'
down_revision: Union[str, None] = 'ddf9e085cc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('event_id', sa.UUID(), nullable=False))
    op.add_column('payment', sa.Column('pay_url', sa.String(), nullable=False))
    op.add_column('payment', sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='paymentstatus'), nullable=False))
    op.create_foreign_key(None, 'payment', 'event', ['event_id'], ['id'])
    op.drop_column('payment', 'currency')
    op.drop_column('payment', 'order_id')
    op.drop_column('payment', 'amount')
    op.drop_column('payment', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_status', postgresql.ENUM('Pending', 'Completed', 'Failed', 'Refunded', name='payment_status'), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'status')
    op.drop_column('payment', 'pay_url')
    op.drop_column('payment', 'event_id')
    # ### end Alembic commands ###
