"""Add default datetime

Revision ID: 96df9d5c0b92
Revises: 7bf722ce96fb
Create Date: 2025-08-19 19:49:29.730471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '96df9d5c0b92'
down_revision: Union[str, None] = '7bf722ce96fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        'event_ticket',
        'last_updated',
        existing_type=sa.DateTime(timezone=True),
        server_default=func.now()
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
