"""change column type

Revision ID: 970e6e95e8ad
Revises: 71189067975f
Create Date: 2025-09-24 21:50:59.336305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970e6e95e8ad'
down_revision: Union[str, None] = '71189067975f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE payment ALTER COLUMN provider TYPE paymentprovider USING provider::paymentprovider")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'provider',
                    existing_type=sa.Enum('VPOS', 'MYAMERIA', 'IDRAM',
                                          'APPLEPAY', name='paymentprovider'),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    # ### end Alembic commands ###
