"""naming

Revision ID: 991e0a14a563
Revises: 27354982ebff
Create Date: 2025-09-23 00:43:40.799991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '991e0a14a563'
down_revision: Union[str, None] = '27354982ebff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'event_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('attendance', 'person_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('event', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('event', 'shared',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('event_ticket', 'person_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('event_ticket', 'event_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('event_ticket', 'is_used',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('event_ticket', 'apple_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('event_ticket', 'google_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('event_ticket', 'last_updated',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('event_ticket', 'is_sent',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('member_card', 'serial_number',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('member_card', 'person_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('member_card', 'apple_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('member_card', 'google_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('member_card', 'last_updated',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('payment', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('payment', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('person', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('venue', 'venue_name', new_column_name='name')
    op.alter_column('venue', 'venue_address', new_column_name='address')
    op.alter_column('venue', 'venue_maps_link', new_column_name='google_maps_link')
    op.add_column('venue', sa.Column('yandex_maps_link',
                  sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('venue_name', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('venue_address', sa.VARCHAR(),
                  autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('venue_maps_link',
                  sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'yandex_maps_link')
    op.drop_column('venue', 'google_maps_link')
    op.drop_column('venue', 'address')
    op.drop_column('venue', 'name')
    op.alter_column('person', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('payment', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('payment', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('member_card', 'last_updated',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('member_card', 'google_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('member_card', 'apple_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('member_card', 'person_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('member_card', 'serial_number',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('event_ticket', 'is_sent',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('event_ticket', 'last_updated',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('event_ticket', 'google_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('event_ticket', 'apple_pass_url',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('event_ticket', 'is_used',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('event_ticket', 'event_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('event_ticket', 'person_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('event', 'shared',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('event', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('attendance', 'person_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('attendance', 'event_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###
