"""empty message

Revision ID: 999ba4471980
Revises: c0dfe00089e0
Create Date: 2025-06-03 23:24:52.809197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999ba4471980'
down_revision: Union[str, None] = 'c0dfe00089e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.rename_table("venues", "venue")
    op.drop_constraint('event_venue_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'venue', ['venue_id'], ['id'])
    op.add_column('person', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_verified')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_venue_id_fkey', 'event', 'venues', ['venue_id'], ['id'])
    op.rename_table("venue", "venues")
    # ### end Alembic commands ###
