"""empty message

Revision ID: b63c2a01de3b
Revises: 9eb97c924950
Create Date: 2026-03-10 16:25:47.469373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63c2a01de3b'
down_revision: Union[str, None] = '9eb97c924950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download')
    op.add_column('event', sa.Column('area', sa.String(), nullable=True))
    op.drop_column('venue', 'area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('event', 'area')
    op.create_table('download',
    sa.Column('Effective user ID', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Stream name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Namespace ID', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Event count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Purchase revenue', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('Transactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Key events', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('# ----------------------------------------', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
