"""is_sent, is_used

Revision ID: c0dfe00089e0
Revises: 46cfcff5b6c3
Create Date: 2025-04-07 15:09:43.635134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dfe00089e0'
down_revision: Union[str, None] = '46cfcff5b6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.add_column('event_ticket', sa.Column('is_sent', sa.Boolean(), nullable=True))
    op.drop_column('event_ticket', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event_ticket', 'is_sent')
    op.drop_column('event_ticket', 'is_used')
    # ### end Alembic commands ###
