"""empty message

Revision ID: ca13bf10cf77
Revises: 831433ce6782
Create Date: 2025-11-29 17:54:00.466601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca13bf10cf77'
down_revision: Union[str, None] = '831433ce6782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_binding',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('masked_card_number', sa.String(), nullable=True),
    sa.Column('card_expiry_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('payment', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('card_binding')
    # ### end Alembic commands ###
