"""empty message

Revision ID: d106e7e27aae
Revises: 1cbf1585ba8f
Create Date: 2025-12-21 15:25:26.428724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd106e7e27aae'
down_revision: Union[str, None] = '1cbf1585ba8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('album_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'album_url')
    # ### end Alembic commands ###
