"""naming membercard->memberpass

Revision ID: dd804e193a1d
Revises: 397ddf42cfb5
Create Date: 2025-09-23 01:33:32.425780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd804e193a1d'
down_revision: Union[str, None] = '397ddf42cfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('member_card', 'member_pass')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.rename_table('member_pass', 'member_card')
