"""payment table changes

Revision ID: df08617822d8
Revises: 8a6e6ebaabc8
Create Date: 2025-09-24 13:03:46.030697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df08617822d8'
down_revision: Union[str, None] = '8a6e6ebaabc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'payment_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_url', sa.VARCHAR(
        length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
