"""switch places

Revision ID: df6ce11ee1cf
Revises: 2b0ab9a99657
Create Date: 2025-04-02 15:16:37.389027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6ce11ee1cf'
down_revision: Union[str, None] = '2b0ab9a99657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_ticket', sa.Column('apple_pass_url', sa.String(), nullable=True))
    op.add_column('event_ticket', sa.Column('google_pass_url', sa.String(), nullable=True))
    op.drop_column('person', 'apple_pass_url')
    op.drop_column('person', 'google_pass_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('google_pass_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('apple_pass_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event_ticket', 'google_pass_url')
    op.drop_column('event_ticket', 'apple_pass_url')
    # ### end Alembic commands ###
