"""empty message

Revision ID: ea1bed3c2df1
Revises: 33096dc8c28d
Create Date: 2025-10-19 18:05:45.194216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea1bed3c2df1'
down_revision: Union[str, None] = '33096dc8c28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_ticket_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='attendance_event_id_fkey'),
    sa.ForeignKeyConstraint(['event_ticket_id'], ['event_ticket.id'], name='attendance_event_ticket_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='attendance_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey'),
    sa.UniqueConstraint('event_id', 'person_id', name='attendance_event_id_person_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
