"""add ticket info in event

Revision ID: ef97873dd71f
Revises: e1d127dada99
Create Date: 2025-06-08 13:08:21.636851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef97873dd71f'
down_revision: Union[str, None] = 'e1d127dada99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ticket_price', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('member_ticket_price', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('max_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'max_capacity')
    op.drop_column('event', 'member_ticket_price')
    op.drop_column('event', 'ticket_price')
    # ### end Alembic commands ###
