"""Date/time changes

Revision ID: f0e3d3af0e69
Revises: 49b4c48ee0c9
Create Date: 2025-08-20 02:18:44.067294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0e3d3af0e69'
down_revision: Union[str, None] = '49b4c48ee0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'event_name', new_column_name='name')

    # add new timestamptz columns
    op.add_column('event', sa.Column('starts_at', sa.DateTime(timezone=True)))
    op.add_column('event', sa.Column('ends_at', sa.DateTime(timezone=True)))

    # if you still have event_date, use it. Otherwise replace '1970-01-01' with your fallback date.
    op.execute("""
        UPDATE event
        SET starts_at = (event_date + start_time)::timestamptz,
            ends_at   = (event_date + end_time)::timestamptz
    """)

    # drop old columns
    op.drop_column('event', 'start_time')
    op.drop_column('event', 'end_time')
    op.drop_column('event', 'event_date')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_name', sa.VARCHAR(),
                  autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('doors_open', postgresql.TIME(
        timezone=True), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('start_time', postgresql.TIME(
        timezone=True), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('end_time', postgresql.TIME(
        timezone=True), autoincrement=False, nullable=True))
    op.create_unique_constraint('event_event_date_key', 'event', ['event_date'])
    op.drop_column('event', 'ends_at')
    op.drop_column('event', 'starts_at')
    op.drop_column('event', 'name')
    # ### end Alembic commands ###
