"""empty message

Revision ID: f1d4c6b652d1
Revises: fe77139280a9
Create Date: 2025-10-25 14:29:32.056374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d4c6b652d1'
down_revision: Union[str, None] = 'fe77139280a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_pass', 'apple_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('member_pass', 'google_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_pass', 'google_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('member_pass', 'apple_pass_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
