"""rename column

Revision ID: ffa47fd0c1de
Revises: df08617822d8
Create Date: 2025-09-24 14:54:18.154067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa47fd0c1de'
down_revision: Union[str, None] = 'df08617822d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_provider', new_column_name='provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_provider', sa.VARCHAR(
        length=50), autoincrement=False, nullable=False))
    op.drop_column('payment', 'provider')
    # ### end Alembic commands ###
